name: GitHub Actions Lint with actionlint

on:
    workflow_call:

permissions: {}

jobs:
    actionlint:
        name: Run actionlint
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
              with:
                  persist-credentials: false

            - name: Run actionlint
              uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 # v1.7.11
              with:
                  args: -color
